guard :minitest,
  test_folders: "spec",
  test_file_patterns: "*_spec.rb",
  include: ["lib", "spec"] do
  watch(%r{^spec/(.*)_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$}) { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^spec/spec_helper\.rb$}) { "spec" }
end

# vim: set ft=ruby:
