guard :minitest,
  test_folders: "spec",
  test_file_patterns: "*_spec.rb",
  include: ["lib", "spec"] do
  watch(%r{^spec/spec_helper\.rb$}) { "spec" }
  watch(%r{^spec/(.*)_spec\.rb$})

  watch(%r{^lib/genconfig\.rb$}) { "spec" }
  watch(%r{^lib/(.+)\.rb$}) { |m| ["spec/unit/#{m[1]}_spec.rb", "spec/integration/#{m[1]}_spec.rb"] }
end

# vim: set ft=ruby:
