[Global]
seed = 9
planetDataPath = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SpaceEngineers\\Content\\Data\\PlanetDataFiles"
planetGeneratorDefinitionsPathArray = [
  "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SpaceEngineers\\Content\\Data\\PlanetGeneratorDefinitions.sbc",
  "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SpaceEngineers\\Content\\Data\\Pertam.sbc",
  "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SpaceEngineers\\Content\\Data\\Triton.sbc",
]
makeColouredMaps = true
surfaceHintMaps = true
shape = 1
density = 0.7

[[Planets]]
name = "EarthLike"
resources = [
  { name = "Iron", shallow = true, deep = true },
  { name = "Nickel", shallow = true, deep = true },
  { name = "Silicon", shallow = true, deep = true },
  { name = "Cobalt", shallow = true, deep = true },
  { name = "Magnesium", shallow = false, deep = true },
]

[[Ores]]
name = "Dense Iron"
subtype = "[CM] Dense Iron"
ingots = ["Iron"]
deep_start = 320
deep_size = 200

[[Ores]]
name = "Heazlewoodite"
subtype = "[CM] Heazlewoodite (Ni)"
ingots = ["Nickel"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Cattierite"
subtype = "[CM] Cattierite (Co)"
ingots = ["Cobalt"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Cattierite"
subtype = "[CM] Cattierite (Co)"
ingots = ["Cobalt"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Pyrite"
subtype = "[CM] Pyrite (Fe, Au)"
ingots = ["Iron", "Gold"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Taenite"
subtype = "[CM] Taenite (Fe, Ni)"
ingots = ["Iron", "Nickel"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Cohenite"
subtype = "[CM] Cohenite (Ni, Co)"
ingots = ["Nickel", "Nickel"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Kamacite"
subtype = "[CM] Kamacite (Fe, Ni, Co)"
ingots = ["Iron", "Nickel", "Nickel"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Glaucodot"
subtype = "[CM] Glaucodot (Fe, Co)"
ingots = ["Iron", "Nickel"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Electrum"
subtype = "[PM] Electrum (Au, Ag)"
ingots = ["Gold", "Silver"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Porphyry"
subtype = "[PM] Porphyry (Au)"
ingots = ["Gold"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Sperrylite"
subtype = "[PM] Sperrylite (Pt)"
ingots = ["Platinum"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Niggliite"
subtype = "[PM] Niggliite (Pt)"
ingots = ["Platinum"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Galena"
subtype = "[PM] Galena (Ag)"
ingots = ["Silver"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Chlorargyrite"
subtype = "[PM] Chlorargyrite (Ag)"
ingots = ["Silver"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Cooperite"
subtype = "[PM] Cooperite (Ni, Ag)"
ingots = ["Nickel", "Silver"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Petzite"
subtype = "[PM] Petzite (Ag, Au)"
ingots = ["Silver", "Gold"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Hapkeite"
subtype = "[S] Hapkeite (Fe, Si)"
ingots = ["Iron", "Silicon"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Dolomite"
subtype = "[S] Dolomite (Mg)"
ingots = ["Magnesium"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Sinoite"
subtype = "[S] Sinoite (Si)"
ingots = ["Silicon"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Olivine"
subtype = "[S] Olivine (Si, Mg)"
ingots = ["Silicon", "Magnesium"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Quartz"
subtype = "[S] Quartz (Si)"
ingots = ["Silicon"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Akimotoite"
subtype = "[S] Akimotoite (Si, Mg)"
ingots = ["Silicon", "Magnesium"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Wadsleyite"
subtype = "[S] Wadsleyite (Si, Mg)"
ingots = ["Silicon", "Magnesium"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Carnotite"
subtype = "[EI] Carnotite (U)"
ingots = ["Uranium"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Autunite"
subtype = "[EI] Autunite (U)"
ingots = ["Uranium"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200

[[Ores]]
name = "Uraniaurite"
subtype = "[EI] Uraniaurite (U, Au)"
ingots = ["Uranium", "Gold"]
shallow_start = 35
shallow_size = 50
deep_start = 320
deep_size = 200
