[[Ores]]
name = 'Dense Iron'
subtype = '[CM] Dense Iron'
ingots = ['Iron']
class = 'CM'

[[Ores]]
name = 'Heazlewoodite'
subtype = '[CM] Heazlewoodite (Ni)'
ingots = ['Nickel']
class = 'CM'

[[Ores]]
name = 'Catclassite'
subtype = '[CM] Catclassite (Co)'
ingots = ['Cobalt']
class = 'CM'

[[Ores]]
name = 'Catclassite'
subtype = '[CM] Catclassite (Co)'
ingots = ['Cobalt']
class = 'CM'

[[Ores]]
name = 'Pyrite'
subtype = '[CM] Pyrite (Fe, Au)'
ingots = ['Iron', 'Gold']
class = 'CM'

[[Ores]]
name = 'Taenite'
subtype = '[CM] Taenite (Fe, Ni)'
ingots = ['Iron', 'Nickel']
class = 'CM'

[[Ores]]
name = 'Cohenite'
subtype = '[CM] Cohenite (Ni, Co)'
ingots = ['Nickel', 'Nickel']
class = 'CM'

[[Ores]]
name = 'Kamacite'
subtype = '[CM] Kamacite (Fe, Ni, Co)'
ingots = ['Iron', 'Nickel', 'Nickel']
class = 'CM'

[[Ores]]
name = 'Glaucodot'
subtype = '[CM] Glaucodot (Fe, Co)'
ingots = ['Iron', 'Nickel']
class = 'CM'

[[Ores]]
name = 'Electrum'
subtype = '[PM] Electrum (Au, Ag)'
ingots = ['Gold', 'Silver']
class = 'PM'

[[Ores]]
name = 'Porphyry'
subtype = '[PM] Porphyry (Au)'
ingots = ['Gold']
class = 'PM'

[[Ores]]
name = 'Sperrylite'
subtype = '[PM] Sperrylite (Pt)'
ingots = ['Platinum']
class = 'PM'

[[Ores]]
name = 'Niggliite'
subtype = '[PM] Niggliite (Pt)'
ingots = ['Platinum']
class = 'PM'

[[Ores]]
name = 'Galena'
subtype = '[PM] Galena (Ag)'
ingots = ['Silver']
class = 'PM'

[[Ores]]
name = 'Chlorargyrite'
subtype = '[PM] Chlorargyrite (Ag)'
ingots = ['Silver']
class = 'PM'

[[Ores]]
name = 'Cooperite'
subtype = '[PM] Cooperite (Ni, Ag)'
ingots = ['Nickel', 'Silver']
class = 'PM'

[[Ores]]
name = 'Petzite'
subtype = '[PM] Petzite (Ag, Au)'
ingots = ['Silver', 'Gold']
class = 'PM'

[[Ores]]
name = 'Hapkeite'
subtype = '[S] Hapkeite (Fe, Si)'
ingots = ['Iron', 'Silicon']
class = 'PM'

[[Ores]]
name = 'Dolomite'
subtype = '[S] Dolomite (Mg)'
ingots = ['Magnesium']
class = 'S'

[[Ores]]
name = 'Sinoite'
subtype = '[S] Sinoite (Si)'
ingots = ['Silicon']
class = 'S'

[[Ores]]
name = 'Olivine'
subtype = '[S] Olivine (Si, Mg)'
ingots = ['Silicon', 'Magnesium']
class = 'S'

[[Ores]]
name = 'Quartz'
subtype = '[S] Quartz (Si)'
ingots = ['Silicon']
class = 'S'

[[Ores]]
name = 'Akimotoite'
subtype = '[S] Akimotoite (Si, Mg)'
ingots = ['Silicon', 'Magnesium']
class = 'S'

[[Ores]]
name = 'Wadsleyite'
subtype = '[S] Wadsleyite (Si, Mg)'
ingots = ['Silicon', 'Magnesium']
class = 'S'

[[Ores]]
name = 'Carnotite'
subtype = '[EI] Carnotite (U)'
ingots = ['Uranium']
class = 'EI'

[[Ores]]
name = 'Autunite'
subtype = '[EI] Autunite (U)'
ingots = ['Uranium']
class = 'EI'

[[Ores]]
name = 'Uraniaurite'
subtype = '[EI] Uraniaurite (U, Au)'
ingots = ['Uranium', 'Gold']
class = 'EI'
