[[Ores]]
name = 'Dense Iron'
subtype = '[CM] Dense Iron'
resources = ['Iron']

[[Ores]]
name = 'Heazlewoodite'
subtype = '[CM] Heazlewoodite (Ni)'
resources = ['Nickel']

[[Ores]]
name = 'Cattierite'
subtype = '[CM] Cattierite (Co)'
resources = ['Cobalt']

[[Ores]]
name = 'Cattierite'
subtype = '[CM] Cattierite (Co)'
resources = ['Cobalt']

[[Ores]]
name = 'Pyrite'
subtype = '[CM] Pyrite (Fe, Au)'
resources = ['Iron', 'Gold']

[[Ores]]
name = 'Taenite'
subtype = '[CM] Taenite (Fe, Ni)'
resources = ['Iron', 'Nickel']

[[Ores]]
name = 'Cohenite'
subtype = '[CM] Cohenite (Ni, Co)'
resources = ['Nickel', 'Nickel']

[[Ores]]
name = 'Kamacite'
subtype = '[CM] Kamacite (Fe, Ni, Co)'
resources = ['Iron', 'Nickel', 'Nickel']

[[Ores]]
name = 'Glaucodot'
subtype = '[CM] Glaucodot (Fe, Co)'
resources = ['Iron', 'Nickel']

[[Ores]]
name = 'Electrum'
subtype = '[PM] Electrum (Au, Ag)'
resources = ['Gold', 'Silver']

[[Ores]]
name = 'Porphyry'
subtype = '[PM] Porphyry (Au)'
resources = ['Gold']

[[Ores]]
name = 'Sperrylite'
subtype = '[PM] Sperrylite (Pt)'
resources = ['Platinum']

[[Ores]]
name = 'Niggliite'
subtype = '[PM] Niggliite (Pt)'
resources = ['Platinum']

[[Ores]]
name = 'Galena'
subtype = '[PM] Galena (Ag)'
resources = ['Silver']

[[Ores]]
name = 'Chlorargyrite'
subtype = '[PM] Chlorargyrite (Ag)'
resources = ['Silver']

[[Ores]]
name = 'Cooperite'
subtype = '[PM] Cooperite (Ni, Ag)'
resources = ['Nickel', 'Silver']

[[Ores]]
name = 'Petzite'
subtype = '[PM] Petzite (Ag, Au)'
resources = ['Silver', 'Gold']

[[Ores]]
name = 'Hapkeite'
subtype = '[S] Hapkeite (Fe, Si)'
resources = ['Iron', 'Silicon']

[[Ores]]
name = 'Dolomite'
subtype = '[S] Dolomite (Mg)'
resources = ['Magnesium']

[[Ores]]
name = 'Sinoite'
subtype = '[S] Sinoite (Si)'
resources = ['Silicon']

[[Ores]]
name = 'Olivine'
subtype = '[S] Olivine (Si, Mg)'
resources = ['Silicon', 'Magnesium']

[[Ores]]
name = 'Quartz'
subtype = '[S] Quartz (Si)'
resources = ['Silicon']

[[Ores]]
name = 'Akimotoite'
subtype = '[S] Akimotoite (Si, Mg)'
resources = ['Silicon', 'Magnesium']

[[Ores]]
name = 'Wadsleyite'
subtype = '[S] Wadsleyite (Si, Mg)'
resources = ['Silicon', 'Magnesium']

[[Ores]]
name = 'Carnotite'
subtype = '[EI] Carnotite (U)'
resources = ['Uranium']

[[Ores]]
name = 'Autunite'
subtype = '[EI] Autunite (U)'
resources = ['Uranium']

[[Ores]]
name = 'Uraniaurite'
subtype = '[EI] Uraniaurite (U, Au)'
resources = ['Uranium', 'Gold']
